services:
    acme.payment.payum.extension.store_notification:
        class: Acme\PaymentBundle\Payum\Extension\StoreNotificationExtension
        arguments:
            - @doctrine

    acme.payment.payum.action.store_notification:
        class: Acme\PaymentBundle\Payum\Action\StoreNotificationAction
        arguments:
            - @doctrine

    acme.payment.payum.api.factory:
        class: Acme\PaymentBundle\Payum\Api\Factory
        arguments:
            - @service_container

    acme.payment.payum.api.factory_via_token:
        class: Acme\PaymentBundle\Payum\Api\Paypal\ExpressCheckout\Nvp\FactoryViaToken
        arguments:
            - @service_container
